export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES'
export const POPULAR_MOVIES_FETCHED = 'POPULAR_MOVIES_FETCHED'

export const FETCH_TOP_RATED_MOVIES = 'FETCH_TOP_RATED_MOVIES'
export const TOP_RATED_MOVIES_FETCHED = 'TOP_RATED_MOVIES_FETCHED'

export const FETCH_UPCOMING_MOVIES = 'FETCH_UPCOMING_MOVIES'
export const UPCOMING_MOVIES_FETCHED = 'UPCOMING_MOVIES_FETCHED'

export const SEARCH_MOVIES = 'SEARCH_MOVIES'
export const MOVIES_SEARCHED = 'MOVIES_SEARCHED'